from __future__ import annotations

from ai.models.llm_provider import BaseLLMProvider


class SinoProvider(BaseLLMProvider):
    """
    Sino Internal Generation Engine V1
    """

    def __init__(self) -> None:

        self.rules = (
            ("fastapi", self.fastapi),
            (".py", self.python),
            (".dart", self.flutter),
            (".html", self.html),
            (".css", self.css),
            (".js", self.javascript),
            (".json", self.json),
        )

    def generate(
        self,
        prompt: str,
    ) -> str:

        text = prompt.lower()

        priority = [
            ("fastapi", self.fastapi),
            ("authentication", self.fastapi),
            ("api", self.fastapi),
            ("flutter", self.flutter),
            (".dart", self.flutter),
            ("html", self.html),
            (".html", self.html),
            ("css", self.css),
            (".css", self.css),
            ("javascript", self.javascript),
            (".js", self.javascript),
            ("json", self.json),
            (".json", self.json),
            ("python", self.python),
            (".py", self.python),
        ]

        for keyword, handler in priority:

            if keyword in text:

                return handler(prompt)

        return self.python(prompt)

    def python(self, prompt: str) -> str:

        return (
            "from __future__ import annotations\n\n"
            'print("Generated by Sino Internal Engine")\n'
        )

    def fastapi(self, prompt: str) -> str:

        return (
            "from fastapi import FastAPI\n\n"
            "app=FastAPI()\n\n"
            "@app.get('/')\n"
            "def root():\n"
            "    return {'status':'running'}\n"
        )

    def flutter(self, prompt: str) -> str:

        return (
            "import 'package:flutter/material.dart';\n\n"
            "void main()=>runApp(const MaterialApp());\n"
        )

    def html(self, prompt: str) -> str:

        return "<!DOCTYPE html><html><body></body></html>"

    def css(self, prompt: str) -> str:

        return "body{margin:0;padding:0;}"

    def javascript(self, prompt: str) -> str:

        return "console.log('Sino Internal Engine');"

    def json(self, prompt: str) -> str:

        return "{}"
