from pathlib import Path


class CodeGenerator:

    def generate(self, project_path, description):

        project = Path(project_path)

        frontend = project / "frontend"
        backend = project / "backend"
        database = project / "database"

        # إنشاء المجلدات إذا لم تكن موجودة
        frontend.mkdir(parents=True, exist_ok=True)
        backend.mkdir(parents=True, exist_ok=True)
        database.mkdir(parents=True, exist_ok=True)

        # Frontend
        (frontend / "README.md").write_text(
f"""Frontend

Project:
{description}

Generated by Sino Builder AI
""",
            encoding="utf-8"
        )

        (frontend / "index.html").write_text(
"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<title>Sino Builder AI</title>
<link rel="stylesheet" href="style.css">
</head>
<body>

<h1>Sino Builder AI</h1>

<p>Project Generated Successfully</p>

<script src="app.js"></script>

</body>
</html>
""",
            encoding="utf-8"
        )

        (frontend / "style.css").write_text(
"""body{

background:#050816;

color:white;

font-family:Arial;

display:flex;

justify-content:center;

align-items:center;

height:100vh;

margin:0;

}
""",
            encoding="utf-8"
        )

        (frontend / "app.js").write_text(
"""console.log("Sino Builder AI Ready");""",
            encoding="utf-8"
        )

        # Backend
        (backend / "README.md").write_text(
f"""Backend

Project:
{description}

Generated by Sino Builder AI
""",
            encoding="utf-8"
        )

        (backend / "config.py").write_text(
'''APP_NAME="Generated Project"

VERSION="1.0.0"
''',
            encoding="utf-8"
        )

        (backend / "main.py").write_text(
'''from fastapi import FastAPI

app = FastAPI(title="Generated API")

@app.get("/")
def root():
    return {"message":"Backend Ready"}
''',
            encoding="utf-8"
        )

        # Database
        (database / "README.md").write_text(
f"""Database

Project:
{description}

Generated by Sino Builder AI
""",
            encoding="utf-8"
        )

        (database / "database.py").write_text(
'''from sqlalchemy import create_engine
from sqlalchemy.orm import sessionmaker

DATABASE_URL = "sqlite:///app.db"

engine = create_engine(DATABASE_URL)

SessionLocal = sessionmaker(bind=engine)
''',
            encoding="utf-8"
        )

        return {
            "success": True,
            "status": "Code Generated",
            "project": project.name
        }
