from __future__ import annotations

from pathlib import Path


class UniversalCodeGenerator:
    """
    Universal source code generator.

    This engine generates production templates
    for any supported file type.
    """

    def generate(
        self,
        file_path: str,
        description: str,
        prompt: str,
    ) -> str:

        extension = Path(file_path).suffix.lower()

        if extension == ".py":
            return self._python(file_path, description)

        if extension == ".dart":
            return self._dart(file_path, description)

        if extension == ".html":
            return self._html(description)

        if extension == ".css":
            return self._css()

        if extension == ".js":
            return self._javascript()

        if extension == ".json":
            return "{}"

        if extension in (".yaml", ".yml"):
            return "# Generated by Sino Builder AI\n"

        if extension == ".md":
            return f"# {description}\n"

        return f"# Generated file: {file_path}\n"

    # ---------------------------------

    def _python(
        self,
        file_path: str,
        description: str,
    ) -> str:

        return f'''"""
{description}

Generated by Sino Builder AI
"""

from fastapi import FastAPI

app = FastAPI()


@app.get("/")
def root():

    return {{
        "status": "running",
        "file": "{file_path}"
    }}
'''

    # ---------------------------------

    def _dart(
        self,
        description: str,
    ) -> str:

        return f'''import 'package:flutter/material.dart';

void main() {{
  runApp(const SinoApp());
}}

class SinoApp extends StatelessWidget {{
  const SinoApp({{super.key}});

  @override
  Widget build(BuildContext context) {{
    return MaterialApp(
      debugShowCheckedModeBanner: false,
      home: Scaffold(
        appBar: AppBar(
          title: const Text("Sino Builder AI"),
        ),
        body: const Center(
          child: Text("{description}"),
        ),
      ),
    );
  }}
}}
'''

    # ---------------------------------

    def _html(
        self,
        description: str,
    ) -> str:

        return f"""<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<title>Sino Builder AI</title>
</head>

<body>

<h1>{description}</h1>

</body>
</html>
"""

    # ---------------------------------

    def _css(self):

        return """body{

font-family:sans-serif;

margin:0;

padding:0;

}
"""

    # ---------------------------------

    def _javascript(self):

        return """console.log("Generated by Sino Builder AI");"""
