import 'package:flutter/material.dart';

void main() {
  runApp(const GeneratedApp());
}

class GeneratedApp extends StatelessWidget {
  const GeneratedApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      debugShowCheckedModeBanner: false,
      home: Scaffold(
        appBar: AppBar(
          title: const Text("
Generate production source code.

Project:
TestAI

File:
frontend/lib/screens/chart.dart

Purpose:
Professional trading chart

Requirements:
منصة تداول ذكاء اصطناعي مثل MT5

Return only valid source code.
"),
        ),
        body: const Center(
          child: Text("Generated by Sino Builder AI"),
        ),
      ),
    );
  }
}
