PUBSPEC = """
name: {project}

description: Generated by SinoBuilderAI

publish_to: "none"

version: 1.0.0+1

environment:

  sdk: ">=3.6.0 <4.0.0"

dependencies:

  flutter:

    sdk: flutter

  cupertino_icons: ^1.0.8

  go_router: ^14.2.0

  flutter_riverpod: ^2.6.1

  dio: ^5.7.0

  flutter_secure_storage: ^9.2.2

  shared_preferences: ^2.3.2

  intl: ^0.19.0

  google_fonts: ^6.2.1

dev_dependencies:

  flutter_test:

    sdk: flutter

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true
"""
MAIN_DART = """
import 'package:flutter/material.dart';

void main() {

  runApp(

    const SinoBuilderApp(),

  );

}

class SinoBuilderApp extends StatelessWidget {

  const SinoBuilderApp({super.key});

  @override

  Widget build(BuildContext context) {

    return MaterialApp(

      debugShowCheckedModeBanner: false,

      title: "{project}",

      home: const Scaffold(

        body: Center(

          child: Text(

            "{project}",

          ),

        ),

      ),

    );

  }

}
"""
APP_STRUCTURE = [
    "flutter/lib",
    "flutter/lib/core",
    "flutter/lib/core/theme",
    "flutter/lib/core/router",
    "flutter/lib/core/network",
    "flutter/lib/core/storage",
    "flutter/lib/features",
    "flutter/lib/features/home",
    "flutter/lib/features/dashboard",
    "flutter/lib/features/settings",
    "flutter/lib/widgets",
    "flutter/assets",
    "flutter/assets/images",
    "flutter/assets/icons",
]
HOME_SCREEN = """
import 'package:flutter/material.dart';

class HomeScreen extends StatelessWidget {

  const HomeScreen({super.key});

  @override
  Widget build(BuildContext context) {

    return const Scaffold(

      body: Center(

        child: Text("Home"),

      ),

    );

  }

}
"""
DASHBOARD_SCREEN = """
import 'package:flutter/material.dart';

class DashboardScreen extends StatelessWidget {

  const DashboardScreen({super.key});

  @override
  Widget build(BuildContext context) {

    return const Scaffold(

      body: Center(

        child: Text("Dashboard"),

      ),

    );

  }

}
"""
SETTINGS_SCREEN = """
import 'package:flutter/material.dart';

class SettingsScreen extends StatelessWidget {

  const SettingsScreen({super.key});

  @override
  Widget build(BuildContext context) {

    return const Scaffold(

      body: Center(

        child: Text("Settings"),

      ),

    );

  }

}
"""
ROUTER = """
import 'package:go_router/go_router.dart';

import '../features/home/home_screen.dart';
import '../features/dashboard/dashboard_screen.dart';
import '../features/settings/settings_screen.dart';

final appRouter = GoRouter(

  initialLocation: "/",

  routes: [

    GoRoute(

      path: "/",

      builder: (context, state) => const HomeScreen(),

    ),

    GoRoute(

      path: "/dashboard",

      builder: (context, state) => const DashboardScreen(),

    ),

    GoRoute(

      path: "/settings",

      builder: (context, state) => const SettingsScreen(),

    ),

  ],

);
"""
APP_THEME = """
import 'package:flutter/material.dart';

final ThemeData appTheme = ThemeData(

  useMaterial3: true,

  colorSchemeSeed: Colors.blue,

  brightness: Brightness.dark,

);
"""
RIVERPOD = """
import 'package:flutter_riverpod/flutter_riverpod.dart';

final appProvider = Provider<String>((ref){

  return "Sino Builder AI";

});
"""
NETWORK = """
import 'package:dio/dio.dart';

final Dio api = Dio(

  BaseOptions(

    connectTimeout: const Duration(seconds: 30),

    receiveTimeout: const Duration(seconds: 30),

    headers: {

      "Accept": "application/json",

    },

  ),

);
"""
SECURE_STORAGE = """
import 'package:flutter_secure_storage/flutter_secure_storage.dart';

const storage = FlutterSecureStorage();
"""
API_SERVICE = """
import '../core/network/api.dart';

class ApiService {

  Future<dynamic> get(String url) async {

    final response = await api.get(url);

    return response.data;

  }

}
"""
FLUTTER_TEMPLATE = {
    "pubspec": PUBSPEC,
    "main": MAIN_DART,
    "router": ROUTER,
    "theme": APP_THEME,
    "provider": RIVERPOD,
    "network": NETWORK,
    "storage": SECURE_STORAGE,
    "service": API_SERVICE,
    "home": HOME_SCREEN,
    "dashboard": DASHBOARD_SCREEN,
    "settings": SETTINGS_SCREEN,
    "structure": APP_STRUCTURE,
}
